{{- if .Values.mail.dev }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "star.fullname" . }}-maildev
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "star.labels" . | nindent 4 }}
    app.kubernetes.io/component: maildev
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      {{- include "star.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: maildev
  template:
    metadata:
      labels:
        {{- include "star.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: maildev
    spec:
      serviceAccountName: {{ include "star.serviceAccountName" . }}
      containers:
        - name: maildev
          image: "maildev/maildev:1.1.0"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: smtp
              containerPort: 25
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 750Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
{{- end }}
