loki:
  config:
    auth_enabled: true
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/boltdb-cache
        cache_ttl: 24h
        shared_store: azure
      azure:
        container_name: loki
        account_name: starloki
        # to pass on the command line loki.config.storage_config.azure.account_key
        account_key:
    schema_config:
      configs:
        - from: 2020-07-01
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: index_
            period: 24h
  resources:
    requests:
      cpu: 25m
      memory: 64Mi

promtail:
  pipelineStages:
    - cri: {}
    - tenant:
        source: namespace
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
