{{ $name := printf "%s-%s" (include "star.fullname" .) "keycloak-extra-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "star.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.mail.dev }}
  TF_VAR_smtp_host: {{ print (include "star.fullname" . ) "-maildev" | b64enc | quote }}
  TF_VAR_smtp_port: {{ "25" | b64enc | quote }}
  TF_VAR_smtp_ssl: {{ "false" | b64enc | quote }}
{{- else }}
  TF_VAR_smtp_host: {{ .Values.mail.host | b64enc | quote }}
  TF_VAR_smtp_port: {{ .Values.mail.port | b64enc | quote }}
  TF_VAR_smtp_username: {{ .Values.mail.username | b64enc | quote }}
  TF_VAR_smtp_password: {{ .Values.mail.password | b64enc | quote }}
  TF_VAR_smtp_ssl: {{ "true" | b64enc | quote }}
{{- end }}
